select
q1.R_STATTIME
,q1.DEVICE_TYPE
,q1.SERVICE_ACCOUNT
,SUM(TRAFFIC_UP) AS TRAFFIC_UP
,SUM(TRAFFIC_DN) AS TRAFFIC_DN
,SUM(TRAFFIC_UP+TRAFFIC_DN) AS TRAFFIC_TOTAL
,TRUNC(DECODE(SUM(TCP_CONNECT_SUC_COUNT),0,-999900,SUM(SHAKEHANDS_DELAY) / SUM(TCP_CONNECT_SUC_COUNT)), 4) AS SHAKEHANDS_DELAY
,TRUNC(DECODE(SUM(TCP_CONNECT_SUC_COUNT),0,-999900,SUM(CLIENT_DELAY) / SUM(TCP_CONNECT_SUC_COUNT)), 4) AS CLIENT_DELAY
,TRUNC(DECODE(SUM(TCP_CONNECT_SUC_COUNT),0,-999900,SUM(SERVER_DELAY) / SUM(TCP_CONNECT_SUC_COUNT)), 4) AS SERVER_DELAY
,TRUNC(DECODE(nvl(SUM(DNS_SESSION_SUC_COUNT),0),0,-999900,SUM(DNS_DELAY) / SUM(DNS_SESSION_SUC_COUNT)), 4) AS DNS_DELAY
,TRUNC(DECODE(nvl(SUM(DNSANALYTIMES),0),0,-9999,SUM(DNSANALYSUCTIMES) / SUM(DNSANALYTIMES)),4)*100 AS DNSANALY_RATE
,TRUNC(DECODE(nvl(SUM(DNSANALYTIMES),0),0,-9999,SUM(DNSRESPONSETIMES) / SUM(DNSANALYTIMES)),4)*100 AS DNSRESPONSE_RATE
,SUM(TCPCONNECT_COUNT) AS TCPCONNECT_COUNT
,SUM(TCPSUCCESSCONNECT_COUNT) AS TCPSUCCESSCONNECT_COUNT
,TRUNC(DECODE(SUM(TCPCONNECT_COUNT),0,-9999,SUM(TCPSUCCESSCONNECT_COUNT) / SUM(TCPCONNECT_COUNT)), 4)*100 AS TCPSUCCESSCONNECT_RATE
,SUM(TCPUPRECON+TCPDOWNRECON) AS TCPDATARECON
,SUM(TCPUPDATAPKGS+TCPDOWNDATAPKGS) AS TCPDATAPKGS
,TRUNC(DECODE(SUM(TCPUPDATAPKGS+TCPDOWNDATAPKGS),0,-9999,SUM(TCPUPRECON+TCPDOWNRECON) / SUM(TCPUPDATAPKGS+TCPDOWNDATAPKGS)), 4)*100 AS TCP_RETRANSMIT_RATE
,TRUNC(DECODE(SUM(TCPUPDATAPKGS),0,-9999,SUM(TCPUPRECON) / SUM(TCPUPDATAPKGS)), 4)*100 AS TCP_UP_RETRANSMIT_RATE
,TRUNC(DECODE(SUM(TCPDOWNDATAPKGS),0,-9999,SUM(TCPDOWNRECON) / SUM(TCPDOWNDATAPKGS)), 4)*100 AS TCP_DN_RETRANSMIT_RATE
,TRUNC(DECODE(SUM(FIRSTHANDSHAKESYN_COUNT),0,-9999,SUM(SECONDHANDSHAKESYNACK_COUNT) / SUM(FIRSTHANDSHAKESYN_COUNT)), 4)*100 AS TCP_FIRST_HANDSHAKE_SUC_RATE
,TRUNC(DECODE(SUM(SECONDHANDSHAKESYNACK_COUNT),0,-9999,SUM(THIRDHANDSHAKEACK_COUNT) / SUM(SECONDHANDSHAKESYNACK_COUNT)), 4)*100 AS TCP_SECOND_HANDSHAKE_SUC_RATE
,TRUNC(DECODE(SUM(HTTP_SESSION_SUC_COUNT),0,-999900,SUM(HTTP_DELAY) / SUM(HTTP_SESSION_SUC_COUNT)), 4) AS HTTP_DELAY
,TRUNC(DECODE(SUM(HTTP_SESSION_SUC_COUNT),0,-999900,SUM(HTTPREQUEST_DELAY) / SUM(HTTP_SESSION_SUC_COUNT)), 4) AS HTTPREQUEST_DELAY
,TRUNC(DECODE(SUM(HTTP_SESSION_SUC_COUNT),0,-999900,SUM(HTTPRESP_DELAY) / SUM(HTTP_SESSION_SUC_COUNT)), 4) AS HTTPRESP_DELAY
,TRUNC(DECODE(SUM(HTTP_SESSION_SUC_COUNT),0,-999900,SUM(HTTPLOAD_DELAY) / SUM(HTTP_SESSION_SUC_COUNT)), 4) AS HTTPLOAD_DELAY
,TRUNC(DECODE(SUM(HTTP_SESSION_SUC_COUNT),0,-999900,SUM(FIRSTBYTE_LOADINGTIME) / SUM(HTTP_SESSION_SUC_COUNT)), 4) AS FIRSTBYTE_LOADINGTIME
,SUM(HTTPGETTIMES) AS HTTPGETTIMES
,SUM(HTTPGETSUCTIMES) AS HTTPGETSUCTIMES
,SUM(HTTPPOSTTIMES) AS HTTPPOSTTIMES
,SUM(HTTPPOSTSUCTIMES) AS HTTPPOSTSUCTIMES
,SUM(RESPONSETIMES) AS RESPONSETIMES
,SUM(RESPONSESUCTIMES) AS RESPONSESUCTIMES
,SUM(RESPONSEERRORTIMES) AS RESPONSEERRORTIMES
,TRUNC(DECODE(SUM(HTTPREQCOUNT),0,-9999,SUM(RESPONSESUCTIMES) / SUM(HTTPREQCOUNT)), 4)*100 AS HTTP_RESP_NORMAL_RATE
,TRUNC(DECODE(SUM(HTTPREQCOUNT),0,-9999,SUM(RESPONSESUCTIMES+RESPONSEREDIRECTTIMES) / SUM(HTTPREQCOUNT)), 4)*100 AS HTTP_RESP_SUC_RATE
,SUM(RESPONSEREDIRECTTIMES) AS RESPONSEREDIRECTTIMES
, TRUNC(DECODE(SUM(RESPONSETIMES),0,-9999,SUM(RESPONSEREDIRECTTIMES) / SUM(RESPONSETIMES)), 4)*100 AS REDIRECT_RATE
from
(select * from REPORT_FLOW_USERQUOTA t
where R_STATTIME >=to_date('2017-07-06 20:00','yyyy-mm-dd hh24:mi')
AND R_STATTIME < to_date('2017-07-06 20:05','yyyy-mm-dd hh24:mi'))q1
JOIN REPORT_FLOW_USERDNS q2
on q1.DEVICE_TYPE=q2.DEVICE_TYPE AND q1.SERVICE_ACCOUNT=q2.SERVICE_ACCOUNT
GROUP BY q1.R_STATTIME,q1.DEVICE_TYPE,q1.SERVICE_ACCOUNT